[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aoc_2024"
path = "src/main.rs"

[dependencies]
regex = "1.11.1"
tracing = "0.1.41"
cached = "0.54.0"
tracing-subscriber = "0.3"
rayon = "1.10"
lru = "0.12.5"